import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	breadcrumb,
	children,
}: Readonly<{
	breadcrumb: React.ReactNode;
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} h-screen flex justify-center items-center flex-col `}
			>
				{breadcrumb}
				{children}
			</body>
		</html>
	);
}
